feat: Add more hepful error-message

diff --git a/.github/workflows/deploy-github-pages.yml b/.github/workflows/deploy-github-pages.yml
--- a/.github/workflows/deploy-github-pages.yml
+++ b/.github/workflows/deploy-github-pages.yml
@@ -150,6 +150,14 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Verify ENV configuration
+        if: env.REGIONS_SHEET_IDS == 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' || env.TXT_APP_NAME == '' || env.ENV_NAME == 'Example'
+        run: |
+          echo "## ⚠️ Configuration error " >> $GITHUB_STEP_SUMMARY
+          echo "- Set the appropriate Google Spreadsheet ID, instead of the default/placeholder-value: `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`" >> $GITHUB_STEP_SUMMARY
+          echo "- Set the appropriate App name (set in `TXT_APP_NAME`, or use the value: `Helpful \n Information`
+          echo "Please change the ENV configuration to real-world values." && exit 1
+
       - name: Checkout
         uses: actions/checkout@v4
 
