fix: Include message as error, instead of text only

diff --git a/.github/workflows/deploy-github-pages.yml b/.github/workflows/deploy-github-pages.yml
--- a/.github/workflows/deploy-github-pages.yml
+++ b/.github/workflows/deploy-github-pages.yml
@@ -156,7 +156,7 @@ jobs:
           echo "### ⚠️ Missing Google Spreadsheet ID" >> $GITHUB_STEP_SUMMARY
           echo "Set the appropriate Google Spreadsheet ID in \`REGIONS_SHEET_IDS\`, instead of the default/placeholder-value: \`xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\`" >> $GITHUB_STEP_SUMMARY
           echo "Edit [\`.github/workflows/deploy-github-pages.yml\`](../../edit/main/.github/workflows/deploy-github-pages.yml) to fix." >> $GITHUB_STEP_SUMMARY
-          echo "Please change the ENV configuration to real-world values" && exit 1
+          echo "::error file=.github/workflows/deploy-github-pages.yml,title=Please change the ENV configuration to real-world values" && exit 1
 
       - name: Checkout
         uses: actions/checkout@v4
